config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :articles
  get '/bulk_upload/articles', to: 'articles#bulk_upload'
  post '/bulk_upload/articles', to: 'articles#bulk_upload_process'
  resources :products
  post '/products/:id/sell', to: 'products#sell'
  get '/bulk_upload/products', to: 'products#bulk_upload'
  post '/bulk_upload/products', to: 'products#bulk_upload_process'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  validates :name, presence: true
  validates :stock, presence: true
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  validates :name, presence: true
  has_many :product_articles
  accepts_nested_attributes_for :product_articles, allow_destroy: true, reject_if: :all_blank
  before_destroy :delete_product_articles

  # This method returns the maximum quantity of the product
  # that we can sell depending on the product articles stock
  # so the number is not exactly accurate since these articles
  # are shared and can be used for other products
  def quantity
    quantity = nil
    product_articles.each do |product_article|
      article = Article.find_by(id: product_article.article_id)
      max_items = (article.stock / product_article.amount).round.to_i
      quantity = max_items if quantity.nil? || max_items < quantity
    end
    quantity.to_i
  end

  private

  def delete_product_articles
    ProductArticle.where(product_id: id).delete_all
  end
end

app/models/product_article.rb
# frozen_string_literal: true

class ProductArticle < ApplicationRecord
  belongs_to :product
  belongs_to :article
  validates :amount, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = 'The Article has been added!'
      redirect_to article_path(@article.id)
    else
      flash[:error] = 'Failed to add the Article'
      render :new
    end
  end

  def show
    @article = Article.find_by(id: params[:id])
  end

  def edit
    @article = Article.find_by(id: params[:id])
  end

  def update
    @article = Article.find_by(id: params[:id])
    if @article.update(article_params)
      flash[:notice] = 'The Article has been updated!'
      redirect_to article_path(@article.id)
    else
      flash[:error] = 'Failed to updates the Article'
      render :new
    end
  end

  def destroy
    @article = Article.find_by(id: params[:id])
    if @article.destroy
      flash[:notice] = 'The Article has been deleted!'
      redirect_to articles_path
    else
      flash[:error] = 'Failed to delete this Article!'
      render :destroy
    end
  end

  def bulk_upload; end

  def bulk_upload_process
    json_file_path = params[:articles][:json_file].tempfile.path
    file = File.open json_file_path
    articles_json = JSON.parse file.read
    UploadArticlesWorker.perform_async(articles_json: articles_json)
    flash[:notice] = 'The Article json file is being processed'
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:name, :stock)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    @articles = Article.all
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = 'The Product has been added!'
      redirect_to product_path(@product.id)
    else
      flash[:error] = 'Failed to add the Product'
      render :new
    end
  end

  def show
    @product = Product.where(id: params[:id]).includes(:product_articles).strict_loading.first
    @articles = Article.all
  end

  def edit
    @product = Product.where(id: params[:id]).includes(:product_articles).strict_loading.first
    @articles = Article.all
  end

  def update
    @product = Product.find_by(id: params[:id])
    if @product.update(product_params)
      flash[:notice] = 'The Product has been updated!'
      redirect_to product_path(@product.id)
    else
      flash[:error] = 'Failed to updates the Product'
      render :new
    end
  end

  def destroy
    @product = Product.find_by(id: params[:id])
    if @product.destroy
      flash[:notice] = 'The Product has been deleted!'
      redirect_to products_path
    else
      flash[:error] = 'Failed to delete this Product!'
      render :destroy
    end
  end

  def sell
    quantity = params[:product][:quantity].to_i
    selling_service = Products::SellingService.new(params[:id], quantity)
    begin
      selling_service.process
      flash[:notice] = 'The Product has been sold'
      redirect_to products_path
    rescue Products::SellingService::NotEnoughStockError => e
      flash[:error] = e.message
      redirect_to products_path
    end
  end

  def bulk_upload; end

  def bulk_upload_process
    json_file_path = params[:products][:json_file].tempfile.path
    file = File.open json_file_path
    products_json = JSON.parse file.read
    UploadProductsWorker.perform_async(products_json: products_json)
    flash[:notice] = 'The Products json file is being processed'
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, product_articles_attributes: %i[id product_id article_id amount _destroy])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <div class="mb-3">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :stock %>
    <%= f.number_field :stock, min: 0, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: 'btn btn-primary btn-lg btn-block' %>
  </div>
<% end %>

app/views/articles/bulk_upload.html.erb
<div class="page-header">
  <h1>
    <span>Bulk Upload Article</span>
  </h1>
  <hr/>
</div>
<%= form_for :articles, method: :post, url: '/bulk_upload/articles' do |form| %>
  <div class="form-group row">
    <div class="col-sm-5">
      <p>Please select the Articles json file</p>
      <%= form.file_field :json_file, class: 'form-control' %>
    </div>
  </div>
  <br/>
  <div class="actions">
    <%= form.submit "Submit", class: 'btn btn-primary btn-lg btn-block' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="page-header">
  <h1>
    <span>Edit Article</span>
  </h1>
  <hr/>
</div>
<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<div class="page-header">
  <h1>
    <span>Articles</span>
    <%= link_to 'Create Article', new_article_path, :class => "btn btn-success create-btn" %>
    <%= link_to 'Create Article in bulk', bulk_upload_articles_path, :class => "btn btn-success create-btn-bulk" %>
  </h1>
  <hr/>
</div>

<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:error] %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:error] %>
  </div>
<% end %>

<div class="container">
  <div class="row align-items-center">
    <div class="col">
      ID
    </div>
    <div class="col">
      Name
    </div>
    <div class="col">
      Stock
    </div>
    <div class="col">
      Edit
    </div>
    <div class="col">
      Delete
    </div>
  </div>
  <% @articles.each do |article| %>
    <div class="row align-items-center mt-3">
      <div class="col">
        <%= article.id %>
      </div>
      <div class="col">
        <%= link_to article.name, article_path(article.id) %>
      </div>
      <div class="col">
        <%= article.stock %>
      </div>
      <div class="col">
        <%= link_to 'Edit', edit_article_path(article.id), :class => "btn btn-primary" %>
      </div>
      <div class="col">
        <%= link_to 'Delete', article_path(article.id), method: :delete, :class => "btn btn-danger" %>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<div class="page-header">
  <h1>
    <span>New Article</span>
  </h1>
  <hr/>
</div>
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<h1>Article <%= @article.id %> </h1>

<dl class="row">
  <dt class="col-sm-3">Name</dt>
  <dd class="col-sm-9"><%= @article.name %></dd>

  <dt class="col-sm-3">Stock</dt>
  <dd class="col-sm-9"><%= @article.stock %></dd>
</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_pack_tag 'application' %>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="logo" viewBox="0 0 118 94">
        <title>Logo</title>
        <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
      </symbol>
      <symbol id="home" viewBox="0 0 16 16">
        <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z"/>
      </symbol>
      <symbol id="speedometer2" viewBox="0 0 16 16">
        <path d="M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z"/>
        <path fill-rule="evenodd" d="M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z"/>
      </symbol>
      <symbol id="table" viewBox="0 0 16 16">
        <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm15 2h-4v3h4V4zm0 4h-4v3h4V8zm0 4h-4v3h3a1 1 0 0 0 1-1v-2zm-5 3v-3H6v3h4zm-5 0v-3H1v2a1 1 0 0 0 1 1h3zm-4-4h4V8H1v3zm0-4h4V4H1v3zm5-3v3h4V4H6zm4 4H6v3h4V8z"/>
      </symbol>
      <symbol id="people-circle" viewBox="0 0 16 16">
        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
        <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
      </symbol>
      <symbol id="grid" viewBox="0 0 16 16">
        <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z"/>
      </symbol>
    </svg>
  </head>

  <body>
    <header class="p-3 bg-dark text-white">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
            <svg class="bi me-2" width="40" height="32" role="img" aria-label="logo"><use xlink:href="#logo"/></svg>
          </a>

          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><%= link_to 'Article', articles_path, class: 'nav-link px-2 text-white' %></li>
            <li><%= link_to 'Products', products_path, class: 'nav-link px-2 text-white' %></li>
          </ul>
        </div>
      </div>
    </header>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <div class="form-group row">
    <%= f.label :name, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-5">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <h3>The product articles</h3>
    <div id='product_articles'>
    <%= f.fields_for :product_articles do |product_article| %>
      <%= render 'product_article_fields', :f => product_article %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'add article', f, :product_articles %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: 'btn btn-primary btn-lg btn-block' %>
  </div>
<% end %>

app/views/products/_product_article_fields.erb
<div class='nested-fields'>
  <div class="form-group row">
    <%= f.label :article_id, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-5">
      <%= f.collection_select(:article_id, @articles, :id, :name, {}, { class: 'form-select' }) %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :amount, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-5">
      <%= f.text_field :amount, class: 'form-control' %>
    </div>
  </div>
  <%= link_to_remove_association "remove article", f %>
</div>

app/views/products/bulk_upload.html.erb
<div class="page-header">
  <h1>
    <span>Bulk Upload Products</span>
  </h1>
  <hr/>
</div>
<%= form_for :products, method: :post, url: '/bulk_upload/products' do |form| %>
  <div class="form-group row">
    <div class="col-sm-5">
      <p>Please select the Products json file</p>
      <%= form.file_field :json_file, class: 'form-control' %>
    </div>
  </div>
  <br/>
  <div class="actions">
    <%= form.submit "Submit", class: 'btn btn-primary btn-lg btn-block' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="page-header">
  <h1>
    <span>Edit Product</span>
  </h1>
  <hr/>
</div>
<%= render 'form', product: @product %>

app/views/products/index.html.erb
<div class="page-header">
  <h1>
    <span>Products</span>
    <%= link_to 'Create Product', new_product_path, :class => "btn btn-success create-btn" %>
    <%= link_to 'Create Products in bulk', bulk_upload_products_path, :class => "btn btn-success create-btn-bulk" %>
  </h1>
  <hr/>
</div>

<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:error] %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:error] %>
  </div>
<% end %>

<div class="container">
  <div class="row align-items-center">
    <div class="col">
      ID
    </div>
    <div class="col">
      Name
    </div>
    <div class="col">
      Inventory*
    </div>
    <div class="col">
      Sell
    </div>
    <div class="col">
      Edit
    </div>
    <div class="col">
      Delete
    </div>
  </div>
  <% @products.each do |product| %>
    <div class="row align-items-center mt-3">
      <div class="col">
        <%= product.id %>
      </div>
      <div class="col">
        <%= link_to product.name, product_path(product.id) %>
      </div>
      <div class="col">
        <%= product.quantity %>
      </div>
      <div class="col">
        <%= form_for :product, method: :post, url: "products/#{product.id}/sell" do |form| %>
        <div class="mb-2">
          <%= form.number_field :quantity, min: 1, max: product.quantity, class: 'form-control', placeholder: 'Quantity' %>
        </div>
        <div class="mb-2">
          <%= form.submit "Sell", class: 'btn btn-outline-success mb-2' %>
        </div>
        <% end %>
      </div>
      <div class="col">
        <%= link_to 'Edit', edit_product_path(product.id), :class => "btn btn-primary" %>
      </div>
      <div class="col">
        <%= link_to 'Delete', product_path(product.id), method: :delete, :class => "btn btn-danger" %>
      </div>
    </div>
  <% end %>
</div>
<hr/>
<div class="container">
<p>This inventory is not that accurate since it depends on product articles that are shared with other products</p>
</div>

app/views/products/new.html.erb
<div class="page-header">
  <h1>
    <span>New Product</span>
  </h1>
  <hr/>
</div>
<%= render 'form', product: @product %>

app/views/products/show.html.erb
<h1>Product <%= @product.id %> </h1>

<dl class="row">
  <dt class="col-sm-3">Name</dt>
  <dd class="col-sm-9"><%= @product.name %></dd>

  <p>Articles</p>
  <dt class="col-sm-3">Name</dt>
  <dt class="col-sm-9">Amount</dt>
  <% @product.product_articles.each do |product_article| %>
    <% article = @articles.select { |article| article.id == product_article.article_id }.first %>
    <dd class="col-sm-3"><%= article.name %></dd>
    <dd class="col-sm-9"><%= product_article.amount %></dd>
  <% end %>
</dl>